import { AlertCircle, BarChart3, LoaderCircle, RefreshCw } from 'lucide-react'
import { useApp } from '../state/AppContext'

const categories = ['PPDT', 'WAT', 'TAT', 'SDT', 'SCT']

export default function HistoryPage() {
  const { history, refreshHistory, historyLoading, historyError, stats } = useApp()
  const scoreFor = (type) => { const items = history.filter((item) => item.type === type); return items.length ? (items.reduce((sum, item) => sum + Number(item.score), 0) / items.length).toFixed(1) : null }
  return <div className="page history-page">
    <section className="analytics-grid"><article className="surface"><header className="surface-header icon-title"><BarChart3/><div><h2>Readiness overview</h2><p>Live average performance by practice type.</p></div></header><div className="score-bars">{categories.map((type) => { const score = scoreFor(type); return <div className="score-row" key={type}><strong>{type}</strong><span className="score-track"><i style={{ width: `${(score ?? 0) * 10}%` }}/></span><b>{score ?? '—'}</b></div> })}</div></article><article className="surface insight-panel"><p className="eyebrow">Current insight</p><h2>{history.some((item) => item.type !== 'PPDT') ? 'Keep balancing your practice' : 'Build breadth next'}</h2><p>Use your next session on the least-practiced category. A broader sample gives you a more useful readiness picture.</p><div className="insight-number"><strong>{stats.sessions}</strong><span>completed sessions</span></div></article></section>
    <header className="section-header"><div><h2>Recent sessions</h2><p>Fetched from your live account.</p></div><button className="text-button" onClick={refreshHistory} disabled={historyLoading}><RefreshCw className={historyLoading ? 'spin' : ''}/> Refresh</button></header>
    {historyLoading && !history.length ? <section className="surface history-state"><LoaderCircle className="spin"/><p>Loading your live practice history…</p></section> : historyError && !history.length ? <section className="surface history-state error"><AlertCircle/><p>{historyError}</p><button className="secondary-button" onClick={refreshHistory}>Try again</button></section> : !history.length ? <section className="surface history-state"><p>No completed live sessions yet. Finish a practice test and it will appear here.</p></section> : <section className="surface table-wrap"><table><thead><tr><th>Test</th><th>Date</th><th>Duration</th><th>Score</th><th>Status</th></tr></thead><tbody>{history.map((item) => <tr key={item.id}><td><strong>{item.type}</strong></td><td>{item.date}</td><td>{item.duration}</td><td className="table-score">{item.score}</td><td><span className="status-badge">{item.status}</span></td></tr>)}</tbody></table>{historyError && <p className="history-warning"><AlertCircle/> Some live history could not be refreshed: {historyError}</p>}</section>}
  </div>
}
