import { AlertCircle, ArrowRight, Clock3, Eye, Lightbulb, LoaderCircle, Play } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { practiceApi } from '../../services/liveApi'
import { useApp } from '../../state/AppContext'
import { SessionHeader, SessionResult, formatClock } from './SessionUI'

const empty = { spot: '', action: '', story: '', logic: '' }
const fields = [
  { key: 'spot', label: 'Spot', title: 'Who and what do you notice?', hint: 'People, approximate age, mood, setting, and relevant details.' },
  { key: 'action', label: 'Action', title: 'What is the central action or theme?', hint: 'Give your story a clear, concise direction.' },
  { key: 'story', label: 'Story', title: 'Write the complete narrative', hint: 'Include the situation, central character, purposeful action, and outcome.' },
  { key: 'logic', label: 'Reasoning', title: 'Why did you interpret it this way?', hint: 'Connect visible details to the story choices you made.' },
]

export default function PpdtSession({ test }) {
  const { addAttempt } = useApp()
  const [phase, setPhase] = useState('setup'); const [observeLeft, setObserveLeft] = useState(30); const [writeLeft, setWriteLeft] = useState(240); const [activeField, setActiveField] = useState(0); const [answers, setAnswers] = useState(empty); const [image, setImage] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState('')
  const filled = useMemo(() => fields.filter((field) => answers[field.key].trim()).length, [answers])
  useEffect(() => { if (phase !== 'observe') return; const timer = setInterval(() => setObserveLeft((value) => { if (value <= 1) { setTimeout(() => setPhase('write'), 0); return 0 } return value - 1 }), 1000); return () => clearInterval(timer) }, [phase])
  useEffect(() => { if (phase !== 'write') return; const timer = setInterval(() => setWriteLeft((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer) }, [phase])
  const begin = async () => { setPhase('loading'); setError(''); try { const nextImage = await practiceApi.getPpdtImage(); if (!nextImage?.id || !nextImage?.url) throw new Error('The live API returned no PPDT image.'); setImage(nextImage); setPhase('observe') } catch (err) { setError(err.message); setPhase('error') } }
  const finish = async () => { if (!answers.spot.trim() || !answers.action.trim() || !answers.story.trim()) return; setPhase('submitting'); setError(''); try { const data = await practiceApi.submitPpdt({ image_id: image.id, spot_text: answers.spot, action_text: answers.action, story_text: answers.story, logic_text: answers.logic }); const score = Number(data.feedback?.overall_score ?? 0); setResult(data); addAttempt({ id: data.session_id, type: 'PPDT', duration: '5 min', score }); setPhase('result') } catch (err) { setError(err.message); setPhase('error') } }
  const restart = () => { setPhase('setup'); setObserveLeft(30); setWriteLeft(240); setActiveField(0); setAnswers(empty); setImage(null); setResult(null); setError('') }
  if (phase === 'loading' || phase === 'submitting') return <div className="session-page"><SessionHeader test={test} phase={phase === 'loading' ? 'Loading live image' : 'AI evaluation'}/><main className="loading-panel"><LoaderCircle className="spin"/><h2>{phase === 'loading' ? 'Loading the active PPDT image…' : 'Evaluating your response…'}</h2><p>This request is being processed by the live API.</p></main></div>
  if (phase === 'error') return <div className="session-page"><SessionHeader test={test} phase="Live API error"/><main className="error-panel"><AlertCircle/><h2>Could not complete the live request</h2><p>{error}</p><button className="primary-button" onClick={restart}>Return to setup</button></main></div>
  if (phase === 'result') return <SessionResult test={test} score={Number(result.feedback?.overall_score ?? 0)} detail={result.feedback?.recommendation || result.feedback?.psychological_analysis || 'Your response was evaluated by the live assessment service.'} metrics={[{ label: 'Sections', value: `${filled}/4` }, { label: 'Story words', value: answers.story.trim().split(/\s+/).length }, { label: 'Observation', value: '30s' }]} onAgain={restart}/>
  if (phase === 'setup') return <div className="session-page"><SessionHeader test={test} phase="Briefing"/><main className="setup-panel ppdt-setup"><div className="setup-banner navy"><Eye/><div><p>Picture perception</p><h2>30s observation · 4m writing</h2></div></div><section className="setup-section"><h3>Four-part response</h3><p>First identify the people and situation, then state the action, build the story, and briefly explain your reasoning.</p></section><section className="instruction-box"><Lightbulb/><div><strong>Observe before you decide</strong><p>Use the visual evidence, but leave room for a plausible and constructive interpretation.</p></div></section><button className="primary-button full" onClick={begin}><Play/> Load live test</button></main></div>
  if (phase === 'observe') return <div className="session-page"><SessionHeader test={test} phase="Observe"/><main className="observation-workspace"><div className="observation-toolbar"><span><Eye/> Observe only</span><strong className={observeLeft <= 5 ? 'urgent-text' : ''}><Clock3/> {observeLeft}s</strong></div><img src={image.url} alt="Live PPDT assessment scene"/><button className="secondary-button" onClick={() => setPhase('write')}>Skip to writing <ArrowRight/></button></main></div>
  const field = fields[activeField]
  return <div className="session-page"><SessionHeader test={test} phase="Write" step={activeField + 1} total={fields.length}/><main className="ppdt-writing"><aside className="response-outline"><div className="writing-clock"><Clock3/> {formatClock(writeLeft)}</div>{fields.map((item, index) => <button key={item.key} className={index === activeField ? 'active' : ''} onClick={() => setActiveField(index)}><span>{index + 1}</span><div><b>{item.label}</b><small>{answers[item.key].trim() ? 'Drafted' : 'Not started'}</small></div></button>)}</aside><section className="response-editor"><p className="eyebrow">{field.label}</p><h2>{field.title}</h2><p>{field.hint}</p><textarea autoFocus value={answers[field.key]} onChange={(event) => setAnswers({ ...answers, [field.key]: event.target.value })} placeholder={`Write your ${field.label.toLowerCase()} response…`}/><div className="editor-footer"><span>{answers[field.key].trim() ? answers[field.key].trim().split(/\s+/).length : 0} words</span>{activeField < fields.length - 1 ? <button className="primary-button" onClick={() => setActiveField(activeField + 1)}>Next section <ArrowRight/></button> : <button className="primary-button" disabled={!answers.spot.trim() || !answers.action.trim() || !answers.story.trim()} onClick={finish}>Finish PPDT</button>}</div></section></main></div>
}
