import { AlertCircle, ArrowLeft, ArrowRight, Clock3, Lightbulb, LoaderCircle, Play } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import useSessionDraft from './useSessionDraft'
import { practiceApi } from '../../services/liveApi'
import { useApp } from '../../state/AppContext'
import { SessionHeader, SessionResult, formatClock } from './SessionUI'

export default function SdtSession({ test }) {
  const TestIcon = test.icon
  const { addAttempt } = useApp()
  const [phase, setPhase] = useState('setup'); const [left, setLeft] = useState(900); const [duration, setDuration] = useState(900); const [index, setIndex] = useState(0); const [prompts, setPrompts] = useState([]); const [answers, setAnswers] = useState([]); const [setCode, setSetCode] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState('')
  const clearDraft = useSessionDraft(test.id, phase, { phase, left, duration, index, prompts, answers, setCode }, (saved) => {
    if (!saved.prompts?.length || !Array.isArray(saved.answers)) return
    setPrompts(saved.prompts); setAnswers(saved.answers); setSetCode(saved.setCode)
    setIndex(saved.index); setLeft(saved.left); setDuration(saved.duration)
    setPhase(['error', 'submitting'].includes(saved.phase) ? 'error' : 'write')
    setError('Your responses were recovered. Check history before retrying a previous submission.')
  })
  const complete = useMemo(() => answers.filter((answer) => answer.trim()).length, [answers])
  useEffect(() => { if (phase !== 'write') return; const timer = setInterval(() => setLeft((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer) }, [phase])
  const begin = async () => { setPhase('loading'); setError(''); try { const data = await practiceApi.getSdtPrompts(); if (!data.prompts?.length) throw new Error('The live API returned no SDT prompts.'); const seconds = Number(data.total_time_seconds) || 900; setPrompts(data.prompts); setAnswers(data.prompts.map(() => '')); setSetCode(data.set_code); setDuration(seconds); setLeft(seconds); setPhase('write') } catch (err) { setError(err.message); setPhase('error') } }
  const finish = async () => { if (complete !== prompts.length) return; setPhase('submitting'); setError(''); try { const responses = prompts.map((prompt, itemIndex) => ({ prompt, response: answers[itemIndex] })); const data = await practiceApi.submitSdt(responses, setCode); const score = Number(data.feedback?.overall_score ?? 0); setResult(data); addAttempt({ id: data.session_id, type: 'SDT', duration: `${Math.max(1, Math.round((duration - left) / 60))} min`, score, feedback: data.feedback, responses }); setPhase('result') } catch (err) { setError(err.message); setPhase('error') } }
  const restart = () => { clearDraft(); setPhase('setup'); setLeft(900); setDuration(900); setIndex(0); setPrompts([]); setAnswers([]); setSetCode(null); setResult(null); setError('') }
  if (phase === 'loading' || phase === 'submitting') return <div className="session-page"><SessionHeader test={test} phase={phase === 'loading' ? 'Loading live set' : 'AI evaluation'}/><main className="loading-panel"><LoaderCircle className="spin"/><h2>{phase === 'loading' ? 'Loading the active SDT prompts…' : 'Evaluating your responses…'}</h2><p>This request is being processed by the live API.</p></main></div>
  if (phase === 'error') return <div className="session-page"><SessionHeader test={test} phase="Live API error"/><main className="error-panel" role="alert"><AlertCircle/><h2>Could not complete the live request</h2><p>{error}</p>{prompts.length > 0 && <><p>Your responses are preserved. Check history before retrying a timed-out submission.</p><button className="primary-button" disabled={complete !== prompts.length} onClick={finish}>Retry submission</button><button className="secondary-button" onClick={() => setPhase('write')}>Review answers</button></>}<button className="secondary-button" onClick={restart}>Discard and return to setup</button></main></div>
  if (phase === 'result') return <SessionResult test={test} score={Number(result.feedback?.overall_score ?? 0)} detail={result.feedback?.recommendation || result.feedback?.self_perception_summary || 'Your descriptions were evaluated by the live assessment service.'} metrics={[{ label: 'Sections', value: `${complete}/${prompts.length}` }, { label: 'Total words', value: answers.join(' ').trim().split(/\s+/).length }]} onAgain={restart} feedback={result.feedback}/>
  if (phase === 'setup') return <div className="session-page"><SessionHeader test={test} phase="Briefing"/><main className="setup-panel"><div className="setup-banner blue"><TestIcon/><div><p>Multi-section reflection</p><h2>Live prompt set · 15 minutes</h2></div></div><section className="setup-section"><h3>Describe one coherent person</h3><p>Answer every section honestly. Strengths, limitations, and aspirations should feel specific and consistent.</p></section><section className="instruction-box"><Lightbulb/><div><strong>Use examples, not labels</strong><p>Instead of “hardworking,” explain what dependable effort looks like in your daily life.</p></div></section><button className="primary-button full" onClick={begin}><Play/> Load live test</button></main></div>
  const answer = answers[index] || ''
  return <div className="session-page"><SessionHeader test={test} phase="Write" step={index + 1} total={prompts.length}/><main className="sdt-workspace"><aside className="sdt-map"><div className="writing-clock"><Clock3/> {formatClock(left)}</div><p>{complete} of {prompts.length} sections drafted</p><div className="mini-progress"><i style={{ width: `${complete / prompts.length * 100}%` }}/></div>{prompts.map((prompt, itemIndex) => <button key={`${itemIndex}-${prompt}`} className={itemIndex === index ? 'active' : ''} onClick={() => setIndex(itemIndex)}><span>{itemIndex + 1}</span><small>{answers[itemIndex].trim() ? 'Drafted' : 'Open'}</small></button>)}</aside><section className="response-editor"><p className="eyebrow">Perspective {index + 1}</p><h2>{prompts[index]}</h2><p>Be specific, balanced, and grounded in observable behavior.</p><textarea aria-label={prompts[index]} maxLength={2000} autoFocus value={answer} onChange={(event) => setAnswers(answers.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder="Write your response…"/><div className="editor-footer"><button className="secondary-button" disabled={index === 0} onClick={() => setIndex(index - 1)}><ArrowLeft/> Previous</button><span>{answer.trim() ? answer.trim().split(/\s+/).length : 0} words</span>{index < prompts.length - 1 ? <button className="primary-button" onClick={() => setIndex(index + 1)}>Next <ArrowRight/></button> : <button className="primary-button" disabled={complete !== prompts.length} onClick={finish}>Finish SDT</button>}</div></section></main></div>
}
