import { AlertCircle, ArrowRight, Clock3, Eye, Lightbulb, LoaderCircle, Play } from 'lucide-react'
import { useEffect, useState } from 'react'
import { WRITING_PROMPTS } from '../../data/tests'
import { practiceApi } from '../../services/liveApi'
import { useApp } from '../../state/AppContext'
import { SessionHeader, SessionResult, formatClock } from './SessionUI'

export default function TatSession({ test }) {
  const { addAttempt } = useApp()
  const [phase, setPhase] = useState('setup'); const [observeLeft, setObserveLeft] = useState(30); const [writeLeft, setWriteLeft] = useState(240); const [story, setStory] = useState(''); const [image, setImage] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState('')
  useEffect(() => { if (phase !== 'observe') return; const timer = setInterval(() => setObserveLeft((value) => { if (value <= 1) { setTimeout(() => setPhase('write'), 0); return 0 } return value - 1 }), 1000); return () => clearInterval(timer) }, [phase])
  useEffect(() => { if (phase !== 'write') return; const timer = setInterval(() => setWriteLeft((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer) }, [phase])
  const begin = async () => { setPhase('loading'); setError(''); try { const data = await practiceApi.getTatImage(); const nextImage = data.images?.[0]; if (!nextImage?.id || !nextImage?.url) throw new Error('The live API returned no TAT image.'); setImage(nextImage); setPhase('observe') } catch (err) { setError(err.message); setPhase('error') } }
  const finish = async () => { setPhase('submitting'); setError(''); try { const data = await practiceApi.submitTat(image.id, story); const score = Number(data.feedback?.overall_score ?? 0); setResult(data); addAttempt({ id: data.session_id, type: 'TAT', duration: '5 min', score }); setPhase('result') } catch (err) { setError(err.message); setPhase('error') } }
  const restart = () => { setPhase('setup'); setObserveLeft(30); setWriteLeft(240); setStory(''); setImage(null); setResult(null); setError('') }
  if (phase === 'loading' || phase === 'submitting') return <div className="session-page"><SessionHeader test={test} phase={phase === 'loading' ? 'Loading live image' : 'AI evaluation'}/><main className="loading-panel"><LoaderCircle className="spin"/><h2>{phase === 'loading' ? 'Loading the active TAT image…' : 'Evaluating your story…'}</h2><p>This request is being processed by the live API.</p></main></div>
  if (phase === 'error') return <div className="session-page"><SessionHeader test={test} phase="Live API error"/><main className="error-panel"><AlertCircle/><h2>Could not complete the live request</h2><p>{error}</p><button className="primary-button" onClick={restart}>Return to setup</button></main></div>
  if (phase === 'result') return <SessionResult test={test} score={Number(result.feedback?.overall_score ?? 0)} detail={result.feedback?.recommendation || result.feedback?.psychological_analysis || 'Your story was evaluated by the live assessment service.'} metrics={[{ label: 'Story words', value: story.trim().split(/\s+/).length }, { label: 'Writing time', value: '4 min' }]} onAgain={restart}/>
  if (phase === 'setup') return <div className="session-page"><SessionHeader test={test} phase="Briefing"/><main className="setup-panel"><div className="setup-banner green"><Eye/><div><p>Story interpretation</p><h2>30s observation · 4m writing</h2></div></div><section className="setup-section"><h3>One complete story</h3><p>{WRITING_PROMPTS.tat}</p></section><section className="instruction-box"><Lightbulb/><div><strong>Let the image lead</strong><p>Give the main character a realistic goal, purposeful action, and a credible outcome.</p></div></section><button className="primary-button full" onClick={begin}><Play/> Load live test</button></main></div>
  if (phase === 'observe') return <div className="session-page"><SessionHeader test={test} phase="Observe"/><main className="observation-workspace"><div className="observation-toolbar"><span><Eye/> Observe only</span><strong className={observeLeft <= 5 ? 'urgent-text' : ''}><Clock3/> {observeLeft}s</strong></div><img src={image.url} alt="Live TAT assessment scene"/><button className="secondary-button" onClick={() => setPhase('write')}>Skip to writing <ArrowRight/></button></main></div>
  const words = story.trim() ? story.trim().split(/\s+/).length : 0
  return <div className="session-page"><SessionHeader test={test} phase="Write"/><main className="active-test tat-writing"><div className="writing-head"><div><p className="eyebrow">Your interpretation</p><h2>Build the complete story</h2></div><span className={`countdown ${writeLeft <= 30 ? 'urgent' : ''}`}><Clock3/> {formatClock(writeLeft)}</span></div><div className="story-guide"><span>What led here?</span><span>What does the hero do?</span><span>What is the outcome?</span></div><textarea autoFocus value={story} onChange={(event) => setStory(event.target.value)} placeholder="Write a clear beginning, middle, and end…"/><div className="editor-footer"><span>{words} words</span><button className="primary-button" disabled={words < 20} onClick={finish}>Finish TAT</button></div></main></div>
}
