import { AlertCircle, Clock3, Keyboard, Lightbulb, LoaderCircle, Play, Send } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { practiceApi } from '../../services/liveApi'
import { useApp } from '../../state/AppContext'
import { SessionHeader, SessionResult } from './SessionUI'

export default function TimedPromptSession({ test, mode }) {
  const TestIcon = test.icon; const isWat = mode === 'wat'; const min = isWat ? 10 : 15; const max = isWat ? 20 : 60; const initial = isWat ? 15 : 30
  const { addAttempt } = useApp(); const [phase, setPhase] = useState('setup'); const [secondsPerItem, setSecondsPerItem] = useState(initial); const [prompts, setPrompts] = useState([]); const [setCode, setSetCode] = useState(null); const [index, setIndex] = useState(0); const [left, setLeft] = useState(initial); const [response, setResponse] = useState(''); const responseRef = useRef(''); const [answers, setAnswers] = useState([]); const [result, setResult] = useState(null); const [error, setError] = useState(''); const startedAt = useRef(Date.now()); const itemStartedAt = useRef(Date.now())
  const isSubmittingIndex = useRef(-1)
  const loadAndStart = async () => { setPhase('loading'); setError(''); try { const data = isWat ? await practiceApi.getWatWords(secondsPerItem) : await practiceApi.getSctStems(secondsPerItem); const items = isWat ? data.words : data.stems; if (!items?.length) throw new Error('The live test set is empty.'); isSubmittingIndex.current = -1; setPrompts(items); setSetCode(data.set_code); setIndex(0); setAnswers([]); setLeft(secondsPerItem); startedAt.current = Date.now(); itemStartedAt.current = Date.now(); setPhase('active') } catch (err) { setError(err.message); setPhase('error') } }
  const finish = async (finalAnswers) => { setPhase('submitting'); setError(''); try { const payload = finalAnswers.map((item) => isWat ? { word: item.prompt, response: item.response, response_time_ms: item.elapsedMs } : { stem: item.prompt, response: item.response, response_time_ms: item.elapsedMs }); const data = isWat ? await practiceApi.submitWat(payload, setCode) : await practiceApi.submitSct(payload, setCode); const score = Number(data.feedback?.overall_score ?? 0); setResult(data); addAttempt({ id: data.session_id, type: test.name, duration: `${Math.max(1, Math.round((Date.now() - startedAt.current) / 60000))} min`, score, feedback: data.feedback, responses: payload }); setPhase('result') } catch (err) { setError(err.message); setPhase('error') } }
  const submit = () => { if (phase !== 'active' || isSubmittingIndex.current === index || !prompts[index]) return; isSubmittingIndex.current = index; const next = [...answers, { prompt: prompts[index], response: responseRef.current, elapsedMs: Math.max(0, Date.now() - itemStartedAt.current) }]; setAnswers(next); setResponse(''); responseRef.current = ''; if (index === prompts.length - 1) finish(next); else { setIndex((value) => value + 1); setLeft(secondsPerItem); itemStartedAt.current = Date.now() } }
  useEffect(() => { if (phase !== 'active') return; const timer = setInterval(() => setLeft((value) => { if (value <= 1) { submit(); return secondsPerItem } return value - 1 }), 1000); return () => clearInterval(timer) }, [phase, index, answers, response])
  const restart = () => { isSubmittingIndex.current = -1; setPhase('setup'); setIndex(0); setAnswers([]); setResult(null); setError(''); setPrompts([]) }
  if (phase === 'result') return <SessionResult test={test} score={Number(result.feedback?.overall_score ?? 0).toFixed(1)} detail={result.feedback?.recommendation || result.feedback?.personality_assessment || 'The live evaluation is complete.'} metrics={[{ label: 'Live set', value: setCode || 'Active' }, { label: 'Prompts', value: prompts.length }, { label: 'AI evaluated', value: 'Yes' }]} onAgain={restart} feedback={result.feedback}/>
  if (phase === 'loading' || phase === 'submitting') return <div className="session-page"><SessionHeader test={test} phase={phase === 'loading' ? 'Loading live set' : 'AI evaluation'}/><main className="loading-panel"><LoaderCircle className="spin"/><h2>{phase === 'loading' ? `Loading the active ${test.name} set…` : 'Evaluating your responses…'}</h2><p>This request is being processed by the live API.</p></main></div>
  if (phase === 'error') return <div className="session-page"><SessionHeader test={test} phase="Live API error"/><main className="error-panel"><AlertCircle/><h2>Could not complete the live request</h2><p>{error}</p><button className="primary-button" onClick={restart}>Return to setup</button></main></div>
  if (phase === 'setup') return <div className="session-page"><SessionHeader test={test} phase="Configure"/><main className="setup-panel"><div className={`setup-banner ${test.color}`}><TestIcon/><div><p>{isWat ? 'Rapid association' : 'Timed completion'}</p><h2>Active live set · {secondsPerItem} seconds each</h2></div></div><section className="setup-section"><h3>Set your pace</h3><label className="range-label"><span>Seconds per prompt</span><output>{secondsPerItem}s</output></label><input type="range" min={min} max={max} value={secondsPerItem} step={isWat ? 1 : 5} onChange={(event) => setSecondsPerItem(Number(event.target.value))}/><div className="range-ends"><span>{min}s — challenge</span><span>{max}s — relaxed</span></div></section><section className="instruction-box"><Lightbulb/><div><strong>{isWat ? 'Use your first constructive thought' : 'Complete—do not repeat—the stem'}</strong><p>The prompt set and final AI evaluation are loaded from the production service.</p></div></section><button className="primary-button full" onClick={loadAndStart}><Play/> Load live test</button></main></div>
  return <div className="session-page"><SessionHeader test={test} phase={`Live set ${setCode || ''}`} step={index + 1} total={prompts.length}/><main className="active-test timed-workspace"><aside className="test-context"><span className={`test-icon ${test.color}`}><TestIcon/></span><p>{isWat ? 'Write the first clear thought that comes to mind.' : 'Finish the sentence in your own words.'}</p><div><Keyboard/><span><b>Enter</b> submits</span></div></aside><section className="prompt-workspace"><div className="session-progress"><i style={{ width: `${(index + 1) / prompts.length * 100}%` }}/></div><span className={`countdown ${left <= 5 ? 'urgent' : ''}`}><Clock3/> {left}s</span><p className={isWat ? 'stimulus-word' : 'stimulus-stem'}>{prompts[index]}{!isWat && ' …'}</p><textarea autoFocus value={response} onChange={(event) => { setResponse(event.target.value); responseRef.current = event.target.value }} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} maxLength="1000" placeholder={isWat ? 'Write your immediate response…' : '…finish the sentence'}/><button className="primary-button full" onClick={submit}>{index === prompts.length - 1 ? 'Submit for evaluation' : 'Next prompt'} <Send/></button></section></main></div>
}
